---
- name: Reverse proxy nginx to grafana
  hosts: all
  become: yes
  remote_user: devops

  tasks:

  - name: Create bridge docker network
    docker_network:
      name: nginx_grafana_bridge
      ipam_config:
        - subnet: "172.3.27.0/24"
          gateway: "172.3.27.1"

  - name: Create grafana container
    docker_container:
      name: grafana
      image: grafana/grafana
      state: started
      networks:
        - name: nginx_grafana_bridge
          ipv4_address: "172.3.27.11"
          aliases:
            - aliasedgrafana
      exposed_ports:
        - '3000'
      ports:
        - 3000:3000

  - name: Create nginx container
    docker_container:
      name: nginx
      image: nginx
      state: started
      networks:
        - name: nginx_grafana_bridge
          ipv4_address: "172.3.27.12"
          aliases:
            - aliasednginx
      exposed_ports:
        - '80'
      ports:
        - 80:80
      volumes:
        - /etc/docker/nginx:/etc/nginx/conf.d:rw

  - name: Copy nginx config file to remote host
    copy:
      src: ~/ansible/default.conf
      dest: /etc/docker/nginx/

  - name: Restrict connection to 3000 Grafana port except docker's inner network
    command: iptables -R DOCKER 1 -p tcp -i ext_if ! -s 172.3.27.12 -j DROP