---
- name: Reverse proxy nginx to grafana
  hosts: all
  become: yes
  remote_user: devops

  tasks:

  - name: Create grafana container
    docker_container:
      name: grafana
      image: grafana/grafana
      state: started
      ports:
        - 3000:3000
      volumes: /etc/docker/grafana/

  - name: Create nginx container
    docker_container:
      name: nginx
      image: nginx
      state: started
      links:
        - "grafana:grafana"
      ports:
        - 80:80
      volumes:
        - /etc/docker/nginx/

  - name: Copy nginx config file to remote host
    copy:
      src: ~/ansible/default.conf
      dest: /home/devops/

  - name: Copy our default.conf in nginx container
    command: "docker cp default.conf nginx:/etc/nginx/conf.d/"

  - name: Restart nginx container with new config file
    command: "docker container restart nginx"