---
- name: Create user
  hosts: all
  become: yes

  handlers:
  - name: Restart sshd
    service:
      name: sshd
      state: restarted

  tasks:
  
  - name: Create user accounts
    user:
      name: devops
      groups: "sudo, www-data, docker"
      state: present

  - name: Add authorized key
    authorized_key:
      user: devops
      state: present
      key: "{{ lookup('file', '/$HOME/.ssh/id_rsa.pub') }}"

  - name: "Allow sudo users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers"
      state: present
      regexp: "^%sudo"
      line: "%sudo ALL=(ALL) NOPASSWD: ALL"

  - name: Disable login via password
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"

  - name: Disable root login via SSH
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    notify: "Restart sshd"
  